name: recipe_app_bloc
description: "A Recipe Apps Flutter for Submission"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  awesome_dialog: ^3.0.2
  carousel_slider: ^4.1.1
  google_fonts: ^4.0.4
  infinite_scroll_pagination: ^3.2.0
  shimmer: ^3.0.0
  auto_route: ^8.1.3
  build_runner: ^2.3.3
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  firebase_core: ^2.4.1
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^16.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.0
  permission_handler: ^11.1.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  package_info_plus: ^8.0.0
  flutter_screenutil: ^5.6.1
  keyboard_dismisser: ^3.0.0
  flutter_spinkit: ^5.1.0

  # local-db
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  auto_route_generator: ^8.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
